### ISSUE TITLE
Does it also work for ESP8266?

### ISSUE THREAD

**Issue by jsponz** [vtunr/esp32_binary_merger#1]
Hi,

I find your tool great. Can I use it for ESP8266? 

Is the merging independent of the CPU type? 

Thanks!

**Comment by vtunr** [comment]
Hi @jsponz,

It's just merging binaries together, it's not particularly linked to ESP32. I'm also using to merge bin from STM32 and it works just as good.
So give it a try for ESP8266, and let us know if it worked for you :)

**Comment by jsponz** [comment]
Hi,

I have tested it but I have an issue:

![image](https://user-images.githubusercontent.com/12778286/87045994-db172a00-c1f8-11ea-8bb2-0f5a240e2526.png)

Thanks!

**Comment by jsponz** [comment]
I answer myself :-) 

![image](https://user-images.githubusercontent.com/12778286/87046510-963fc300-c1f9-11ea-852c-c5047c894e42.png)

I test the output later at home :-)

**Comment by jsponz** [comment]
It works perfect!!! Thanks a lot!!!

**Comment by vtunr** [comment]
@jsponz Thanks for the update :)
